// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByO8RaPcfsCJoo2BzSU81MjCHFBUyJyF4',
    appId: '1:588555793266:web:1d711ec395c5394ff5a3eb',
    messagingSenderId: '588555793266',
    projectId: 'union-shop-63006',
    authDomain: 'union-shop-63006.firebaseapp.com',
    storageBucket: 'union-shop-63006.firebasestorage.app',
    measurementId: 'G-4VWKFCKQ11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbW8nXNZvEjE_waELINcKxrew2W2VZni8',
    appId: '1:588555793266:android:dd7494915a4d2f9ff5a3eb',
    messagingSenderId: '588555793266',
    projectId: 'union-shop-63006',
    storageBucket: 'union-shop-63006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXkcm2nsca3lJwv3zsZIew4wbq4zvUPg',
    appId: '1:588555793266:ios:d2bc0d889d82c960f5a3eb',
    messagingSenderId: '588555793266',
    projectId: 'union-shop-63006',
    storageBucket: 'union-shop-63006.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOXkcm2nsca3lJwv3zsZIew4wbq4zvUPg',
    appId: '1:588555793266:ios:d2bc0d889d82c960f5a3eb',
    messagingSenderId: '588555793266',
    projectId: 'union-shop-63006',
    storageBucket: 'union-shop-63006.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByO8RaPcfsCJoo2BzSU81MjCHFBUyJyF4',
    appId: '1:588555793266:web:df655eeb2173cec1f5a3eb',
    messagingSenderId: '588555793266',
    projectId: 'union-shop-63006',
    authDomain: 'union-shop-63006.firebaseapp.com',
    storageBucket: 'union-shop-63006.firebasestorage.app',
    measurementId: 'G-HC45CR6FV9',
  );
}
